# Generated by Django 4.1.7 on 2023-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('gmtCreated', models.DateTimeField(auto_now_add=True)),
                ('gmtModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'counter',
            },
        ),
    ]
